import { useState } from "react";
import { Scale, AlertTriangle, CheckCircle2 } from "lucide-react";
import { Button } from "./ui/button";
import { Checkbox } from "./ui/checkbox";
import axios from "axios";
import { API } from "../App";
import { toast } from "sonner";

const TermsAcceptance = ({ onAccept }) => {
  const [accepted, setAccepted] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleAccept = async () => {
    if (!accepted) {
      toast.error("Please accept the terms and conditions to continue");
      return;
    }

    setLoading(true);
    try {
      await axios.post(`${API}/auth/accept-terms`);
      onAccept();
    } catch (error) {
      toast.error("Failed to save acceptance. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
      <div className="max-w-2xl w-full bg-white rounded-2xl shadow-xl border border-slate-200 overflow-hidden">
        {/* Header */}
        <div className="bg-slate-900 px-6 py-5">
          <div className="flex items-center gap-3">
            <Scale className="w-8 h-8 text-amber-400" />
            <h1 className="text-xl font-bold text-white" style={{ fontFamily: 'Crimson Pro, serif' }}>
              Appeal Case Manager
            </h1>
          </div>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          <div className="text-center">
            <h2 className="text-2xl font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
              Terms & Conditions
            </h2>
            <p className="text-slate-600">
              Please read and accept the following terms before using this application
            </p>
          </div>

          {/* Terms Content */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 space-y-4 max-h-80 overflow-y-auto">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5 shrink-0" />
              <div>
                <h3 className="font-semibold text-amber-900 mb-1">Important Notice & Disclaimer</h3>
              </div>
            </div>

            <div className="space-y-3 text-sm text-amber-800 pl-8">
              <p>
                This application provides AI-assisted document analysis and research support intended to help 
                identify potential issues that may warrant further legal review.
              </p>
              
              <p>
                The information generated by this tool <strong>does not constitute legal advice</strong> and 
                should not be relied upon as a substitute for advice from a qualified Australian legal practitioner.
              </p>
              
              <div className="bg-amber-100 rounded-lg p-3 border border-amber-300">
                <p className="font-semibold text-amber-900 mb-2">User Responsibility:</p>
                <ul className="list-disc list-inside space-y-1">
                  <li>You use this application at your own discretion and risk</li>
                  <li>You are solely responsible for ensuring you have the necessary permissions and legal authority to upload any documents or content</li>
                  <li>The application owner accepts no responsibility for the content uploaded by users</li>
                </ul>
              </div>
              
              <p>
                All information, analysis, and results generated through this application are for informational purposes only and 
                <strong> must be reviewed by a qualified legal professional</strong> before any reliance or action is taken.
              </p>

              <p>
                By accepting these terms, you acknowledge that you have read, understood, and agree to be bound by these conditions.
              </p>
            </div>
          </div>

          {/* Acceptance Checkbox */}
          <div className="flex items-start gap-3 p-4 bg-slate-50 rounded-lg border border-slate-200">
            <Checkbox 
              id="accept-terms" 
              checked={accepted}
              onCheckedChange={setAccepted}
              className="mt-0.5"
              data-testid="accept-terms-checkbox"
            />
            <label 
              htmlFor="accept-terms" 
              className="text-sm text-slate-700 cursor-pointer select-none"
            >
              I have read and understood the terms and conditions. I accept full responsibility for ensuring I have 
              the necessary permissions to upload content, and I understand that all results must be reviewed by a 
              qualified legal professional.
            </label>
          </div>

          {/* Accept Button */}
          <Button
            onClick={handleAccept}
            disabled={!accepted || loading}
            className="w-full bg-slate-900 hover:bg-slate-800 text-white py-3 text-lg font-medium"
            data-testid="accept-terms-btn"
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                Processing...
              </span>
            ) : (
              <span className="flex items-center gap-2">
                <CheckCircle2 className="w-5 h-5" />
                Accept & Continue
              </span>
            )}
          </Button>
        </div>
      </div>
    </div>
  );
};

export default TermsAcceptance;
