import { useState } from "react";
import { Scale, ArrowLeft, ChevronDown, ChevronUp, Search, HelpCircle, FileText, Clock, Shield, CreditCard, Users, Gavel } from "lucide-react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Card, CardContent } from "../components/ui/card";
import { Link } from "react-router-dom";

const faqs = [
  {
    category: "Getting Started",
    icon: HelpCircle,
    questions: [
      {
        q: "What is the Appeal Case Manager?",
        a: "The Appeal Case Manager is an AI-powered tool designed to help families and supporters of convicted individuals identify potential grounds for criminal appeal. It helps organize case documents, generate timelines, and create professional reports that can be shared with legal professionals."
      },
      {
        q: "Who is this tool for?",
        a: "This tool is primarily designed for family members, friends, and supporters of people who have been convicted of criminal offences in Australia. It's also useful for law students, paralegals, and anyone researching criminal appeals. It is NOT a substitute for qualified legal advice."
      },
      {
        q: "Do I need legal experience to use this?",
        a: "No. The tool is designed to be user-friendly and explains legal concepts in plain English. However, we strongly recommend consulting with a qualified criminal lawyer before lodging any appeal."
      }
    ]
  },
  {
    category: "Appeals Process",
    icon: Gavel,
    questions: [
      {
        q: "What are the time limits for lodging an appeal?",
        a: "Time limits vary by state and type of appeal. Generally, appeals against conviction or sentence must be lodged within 28 days of the sentence being handed down. However, courts can grant extensions in certain circumstances. Always check with a lawyer about specific deadlines."
      },
      {
        q: "What are 'grounds for appeal'?",
        a: "Grounds for appeal are the legal reasons why you believe the conviction or sentence was wrong. Common grounds include: errors in the judge's directions to the jury, fresh evidence that wasn't available at trial, inadequate legal representation, and sentencing errors."
      },
      {
        q: "Can I appeal if there's new evidence?",
        a: "Yes, fresh evidence can be grounds for appeal, but it must meet strict criteria. The evidence must: (1) not have been available at the original trial, (2) be credible, and (3) be likely to have affected the outcome. The court will decide whether to admit fresh evidence."
      },
      {
        q: "What's the difference between appealing conviction vs sentence?",
        a: "An appeal against conviction argues the person should not have been found guilty at all. An appeal against sentence accepts the conviction but argues the sentence was too harsh or legally incorrect. You can appeal both, but different grounds apply to each."
      }
    ]
  },
  {
    category: "Using the Tool",
    icon: FileText,
    questions: [
      {
        q: "What documents should I upload?",
        a: "Upload everything related to the case: court transcripts, judge's sentencing remarks, witness statements, police evidence briefs, character references, medical reports, and any other relevant documents. The more information the AI has, the better the analysis."
      },
      {
        q: "How does the AI identify grounds for appeal?",
        a: "The AI analyzes your uploaded documents looking for patterns that commonly indicate appealable errors: inconsistencies in evidence, procedural irregularities, potential misdirections by the judge, and gaps in the prosecution's case. It cross-references against Australian criminal law."
      },
      {
        q: "Are the AI-generated reports legally accurate?",
        a: "The reports provide a starting point for analysis and highlight potential issues. However, they are generated by AI and may contain errors or miss important nuances. Always have a qualified lawyer review any AI-generated analysis before taking legal action."
      },
      {
        q: "Can I edit the timeline and grounds?",
        a: "Yes. The AI generates initial suggestions, but you can add, edit, or remove timeline events and grounds of merit. You know your case best - use the AI as a starting point and refine from there."
      }
    ]
  },
  {
    category: "Payments & Pricing",
    icon: CreditCard,
    questions: [
      {
        q: "What does the free version include?",
        a: "Free features include: unlimited document uploads, AI-generated timeline, Quick Summary reports, case strength meter, deadline tracking, and the appeal checklist. You can manage your entire case without paying."
      },
      {
        q: "What are the paid features?",
        a: "Paid features include: Full Detailed Reports ($29 AUD) which provide comprehensive legal analysis with case citations, Extensive Log Reports ($39 AUD) for exhaustive documentation, and Grounds of Merit Details ($50 AUD) for in-depth analysis of each appeal ground."
      },
      {
        q: "Is my payment secure?",
        a: "Yes. All payments are processed through PayPal's secure payment system. We never see or store your credit card details."
      },
      {
        q: "Can I get a refund?",
        a: "Due to the nature of AI-generated content, refunds are generally not available once a report has been generated. If you experience technical issues preventing report delivery, please contact us."
      }
    ]
  },
  {
    category: "Privacy & Security",
    icon: Shield,
    questions: [
      {
        q: "Is my case information confidential?",
        a: "Yes. Your case data is stored securely and is only accessible to you. We do not share individual case information with anyone. Aggregated, anonymized statistics may be used to improve the service."
      },
      {
        q: "Who can see my documents?",
        a: "Only you can see your uploaded documents and case details. Our system processes documents automatically - no humans review your files unless you specifically request support assistance."
      },
      {
        q: "Can I delete my data?",
        a: "Yes. You can delete individual documents, notes, or entire cases at any time. Deleted data is permanently removed from our systems."
      }
    ]
  },
  {
    category: "Getting Legal Help",
    icon: Users,
    questions: [
      {
        q: "How do I find a criminal appeal lawyer?",
        a: "Check our Lawyer Directory page for links to criminal appeal specialists in each state. You can also contact your state's Legal Aid office, Law Society, or Bar Association for referrals."
      },
      {
        q: "What is Legal Aid and am I eligible?",
        a: "Legal Aid provides free or low-cost legal help to people who can't afford a private lawyer. Eligibility depends on your income, assets, and the nature of your case. Each state has different criteria - contact your local Legal Aid office for a means test."
      },
      {
        q: "Can this tool replace a lawyer?",
        a: "No. This tool helps you organize information and identify potential issues, but it cannot replace qualified legal advice. Criminal appeals are complex and the consequences of errors are serious. Always consult a lawyer before taking any legal action."
      }
    ]
  }
];

const FAQPage = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [openItems, setOpenItems] = useState({});

  const toggleItem = (categoryIndex, questionIndex) => {
    const key = `${categoryIndex}-${questionIndex}`;
    setOpenItems(prev => ({
      ...prev,
      [key]: !prev[key]
    }));
  };

  const filteredFaqs = searchQuery
    ? faqs.map(category => ({
        ...category,
        questions: category.questions.filter(
          q => q.q.toLowerCase().includes(searchQuery.toLowerCase()) ||
               q.a.toLowerCase().includes(searchQuery.toLowerCase())
        )
      })).filter(category => category.questions.length > 0)
    : faqs;

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-slate-900 px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Scale className="w-7 h-7 text-amber-500" />
            <span className="text-lg font-semibold text-white" style={{ fontFamily: 'Crimson Pro, serif' }}>
              Appeal Case Manager
            </span>
          </div>
          <Link to="/">
            <Button variant="outline" className="border-slate-600 text-slate-300 hover:bg-slate-800">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
          </Link>
        </div>
      </header>

      {/* Hero */}
      <section className="bg-slate-900 px-6 py-12 border-b border-slate-800">
        <div className="max-w-4xl mx-auto text-center">
          <HelpCircle className="w-12 h-12 text-amber-500 mx-auto mb-4" />
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-4" style={{ fontFamily: 'Crimson Pro, serif' }}>
            Frequently Asked Questions
          </h1>
          <p className="text-slate-400 max-w-2xl mx-auto mb-8">
            Find answers to common questions about criminal appeals and using the Appeal Case Manager.
          </p>
          
          {/* Search */}
          <div className="max-w-md mx-auto relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
            <Input
              type="text"
              placeholder="Search questions..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10 bg-slate-800 border-slate-700 text-white placeholder:text-slate-500"
            />
          </div>
        </div>
      </section>

      {/* FAQ Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        {filteredFaqs.length === 0 ? (
          <Card className="p-8 text-center">
            <p className="text-slate-500">No questions found matching "{searchQuery}"</p>
          </Card>
        ) : (
          <div className="space-y-8">
            {filteredFaqs.map((category, categoryIndex) => (
              <div key={categoryIndex}>
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-amber-100 rounded-lg flex items-center justify-center">
                    <category.icon className="w-5 h-5 text-amber-600" />
                  </div>
                  <h2 className="text-xl font-bold text-slate-900" style={{ fontFamily: 'Crimson Pro, serif' }}>
                    {category.category}
                  </h2>
                </div>
                
                <Card className="divide-y divide-slate-100">
                  {category.questions.map((item, questionIndex) => {
                    const isOpen = openItems[`${categoryIndex}-${questionIndex}`];
                    return (
                      <div key={questionIndex}>
                        <button
                          onClick={() => toggleItem(categoryIndex, questionIndex)}
                          className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-slate-50 transition-colors"
                        >
                          <span className="font-medium text-slate-900 pr-4">{item.q}</span>
                          {isOpen ? (
                            <ChevronUp className="w-5 h-5 text-slate-400 flex-shrink-0" />
                          ) : (
                            <ChevronDown className="w-5 h-5 text-slate-400 flex-shrink-0" />
                          )}
                        </button>
                        {isOpen && (
                          <div className="px-6 pb-4">
                            <p className="text-slate-600 leading-relaxed">{item.a}</p>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </Card>
              </div>
            ))}
          </div>
        )}

        {/* Still have questions */}
        <Card className="mt-12 bg-gradient-to-r from-slate-900 to-slate-800 border-0">
          <CardContent className="p-8 text-center">
            <h3 className="text-xl font-bold text-white mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
              Still have questions?
            </h3>
            <p className="text-slate-400 mb-4">
              Can't find what you're looking for? Get in touch with us.
            </p>
            <Link to="/contact">
              <Button className="bg-amber-600 text-white hover:bg-amber-700">
                Contact Us
              </Button>
            </Link>
          </CardContent>
        </Card>
      </main>
    </div>
  );
};

export default FAQPage;
