import { Scale, FileText, Clock, Shield, Upload, BarChart3, FileCheck, Users, ChevronRight, AlertTriangle } from "lucide-react";
import { Button } from "../components/ui/button";
import { Link } from "react-router-dom";

const LandingPage = () => {
  const handleLogin = () => {
    const redirectUrl = window.location.origin + "/dashboard";
    window.location.href = `https://auth.emergentagent.com/?redirect=${encodeURIComponent(redirectUrl)}`;
  };

  return (
    <div className="min-h-screen bg-slate-50" style={{ fontFamily: 'Manrope, sans-serif' }}>
      {/* Header */}
      <header className="bg-slate-900 border-b border-slate-800">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Scale className="w-8 h-8 text-amber-500" />
            <span className="text-xl font-semibold text-white tracking-tight" style={{ fontFamily: 'Crimson Pro, serif' }}>
              Appeal Case Manager
            </span>
          </div>
          <div className="flex items-center gap-4">
            <Link to="/professional-summary" className="hidden md:block">
              <Button variant="ghost" className="text-slate-300 hover:text-white hover:bg-slate-800">
                For Legal Professionals
              </Button>
            </Link>
            <Link to="/terms" className="hidden md:block">
              <Button variant="ghost" className="text-slate-300 hover:text-white hover:bg-slate-800">
                Terms of Service
              </Button>
            </Link>
            <Button 
              onClick={handleLogin}
              data-testid="login-btn"
              className="bg-amber-600 text-white hover:bg-amber-700 rounded-md px-5 py-2 font-medium"
            >
              Sign In
            </Button>
          </div>
        </div>
      </header>

      {/* CRITICAL DISCLAIMER - Large, Bold, Red */}
      <section className="bg-red-700 border-y-4 border-red-900">
        <div className="max-w-5xl mx-auto px-6 py-8">
          <div className="flex items-start gap-4">
            <div className="w-14 h-14 bg-white rounded-full flex items-center justify-center shrink-0 shadow-lg">
              <AlertTriangle className="w-8 h-8 text-red-700" />
            </div>
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-white mb-4 tracking-tight" style={{ fontFamily: 'Crimson Pro, serif' }}>
                IMPORTANT LEGAL DISCLAIMER
              </h2>
              <div className="space-y-3 text-white">
                <p className="text-lg md:text-xl font-semibold leading-relaxed">
                  This application does <span className="underline decoration-4">NOT</span> provide legal advice. 
                  The creator, Debra King, is <span className="underline decoration-4">NOT</span> a qualified lawyer.
                </p>
                <p className="text-base md:text-lg leading-relaxed opacity-95">
                  All information, analysis, and reports generated by this tool are for <strong>informational and research purposes only</strong>. 
                  Any results must be independently reviewed and verified by a qualified Australian legal practitioner before any action is taken.
                </p>
                <p className="text-base md:text-lg leading-relaxed opacity-95">
                  By using this application, you accept full responsibility for your use of the service and agree to our 
                  <Link to="/terms" className="underline font-semibold hover:text-amber-200 ml-1">Terms of Service</Link>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Hero Section */}
      <section className="bg-white border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-6 py-16 md:py-20">
          <div className="max-w-4xl">
            <p className="text-amber-700 font-semibold text-sm uppercase tracking-wider mb-4">
              Criminal Appeal Research Tool
            </p>
            <h1 
              className="text-4xl md:text-5xl lg:text-6xl font-bold text-slate-900 tracking-tight leading-tight mb-6"
              style={{ fontFamily: 'Crimson Pro, serif' }}
            >
              Organise Case Documents.<br />
              Identify Appeal Issues.
            </h1>
            <p className="text-lg md:text-xl text-slate-600 leading-relaxed mb-8 max-w-3xl">
              A document analysis and case organisation tool designed to assist with identifying potential 
              appeal issues in homicide cases under NSW State and Australian Federal law.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button
                onClick={handleLogin}
                data-testid="hero-login-btn"
                className="bg-slate-900 text-white hover:bg-slate-800 rounded-md px-8 py-3 text-lg font-medium inline-flex items-center gap-2"
              >
                Get Started
                <ChevronRight className="w-5 h-5" />
              </Button>
              <Link to="/terms">
                <Button
                  variant="outline"
                  className="border-slate-300 text-slate-700 hover:bg-slate-50 rounded-md px-8 py-3 text-lg font-medium"
                >
                  Read Terms First
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* What This Tool Does */}
      <section className="bg-slate-50 border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-6 py-16">
          <div className="text-center mb-12">
            <h2 
              className="text-3xl md:text-4xl font-bold text-slate-900 tracking-tight mb-4"
              style={{ fontFamily: 'Crimson Pro, serif' }}
            >
              Research & Organisation Features
            </h2>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              Tools to help organise case materials and identify potential issues for further legal review
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* Feature 1 */}
            <div className="bg-white border border-slate-200 rounded-lg p-6 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-slate-100 rounded-lg flex items-center justify-center mb-4">
                <Upload className="w-6 h-6 text-slate-700" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                Document Management
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                Upload, categorise, and organise case documents including transcripts, evidence, and court records in one secure location.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="bg-white border border-slate-200 rounded-lg p-6 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-slate-100 rounded-lg flex items-center justify-center mb-4">
                <Clock className="w-6 h-6 text-slate-700" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                Timeline Generation
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                AI-assisted chronological organisation of events extracted from uploaded documents to help visualise case progression.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="bg-white border border-slate-200 rounded-lg p-6 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-slate-100 rounded-lg flex items-center justify-center mb-4">
                <BarChart3 className="w-6 h-6 text-slate-700" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                Issue Identification
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                AI analysis to flag potential issues that may warrant further review by qualified legal professionals.
              </p>
            </div>

            {/* Feature 4 */}
            <div className="bg-white border border-slate-200 rounded-lg p-6 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-slate-100 rounded-lg flex items-center justify-center mb-4">
                <FileCheck className="w-6 h-6 text-slate-700" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                Report Generation
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                Generate structured summaries and reports to assist with organising information for legal consultation.
              </p>
            </div>

            {/* Feature 5 */}
            <div className="bg-white border border-slate-200 rounded-lg p-6 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-slate-100 rounded-lg flex items-center justify-center mb-4">
                <FileText className="w-6 h-6 text-slate-700" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                OCR Text Extraction
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                Extract text from scanned documents and images to make content searchable and analysable.
              </p>
            </div>

            {/* Feature 6 */}
            <div className="bg-white border border-slate-200 rounded-lg p-6 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-slate-100 rounded-lg flex items-center justify-center mb-4">
                <Shield className="w-6 h-6 text-slate-700" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                Secure Storage
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                Case data stored securely with user authentication. You control your documents and can request deletion at any time.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* About the Creator */}
      <section className="bg-slate-900 border-b border-slate-800">
        <div className="max-w-5xl mx-auto px-6 py-16">
          <div className="grid md:grid-cols-3 gap-8">
            {/* Left - Creator Info */}
            <div className="md:col-span-2">
              <p className="text-amber-500 font-semibold text-sm uppercase tracking-wider mb-4">
                About the Creator
              </p>
              <h2 
                className="text-3xl md:text-4xl font-bold text-white tracking-tight mb-6"
                style={{ fontFamily: 'Crimson Pro, serif' }}
              >
                A Personal Mission
              </h2>
              
              {/* NOT A LAWYER DISCLAIMER */}
              <div className="bg-red-900/50 border-l-4 border-red-500 p-4 mb-6 rounded-r-lg">
                <p className="text-red-100 font-semibold text-lg">
                  Debra King is NOT a qualified lawyer.
                </p>
                <p className="text-red-200 text-sm mt-1">
                  She has spent years self-educating on NSW and Australian Federal criminal law, but holds no formal legal qualifications.
                </p>
              </div>

              <div className="space-y-4 text-slate-300 leading-relaxed">
                <p>
                  I created this application because I have two best mates who are incarcerated, and I refuse to stand by while the system fails them.
                </p>
                <p>
                  <strong className="text-amber-400">Josh Homann</strong> has been incarcerated for over 10 years of a 30-year sentence. 
                  Straight after sentencing, he was told he had no grounds for appeal.
                </p>
                <p>
                  <strong className="text-amber-400">Brad Fletcher</strong> has been on remand for over 2 years, still awaiting trial.
                </p>
                <p>
                  I've spent years manually searching through case files, comparing and assessing appeals to understand what made them 
                  successful or unsuccessful. I've become well-educated in criminal law—murder, manslaughter, and mens rea—to the point 
                  where I can recite most sections of the relevant Acts without reference.
                </p>
              </div>
            </div>

            {/* Right - Quote */}
            <div className="flex items-center">
              <div className="bg-slate-800 border border-slate-700 rounded-lg p-6">
                <blockquote className="text-white italic text-lg leading-relaxed" style={{ fontFamily: 'Crimson Pro, serif' }}>
                  "I just wanted to create something that could possibly assist others without them having to spend years 
                  working this out themselves. I'm sure this will help lawyers at all levels too."
                </blockquote>
                <p className="text-amber-500 font-semibold mt-4">— Debra King</p>
                <p className="text-slate-400 text-sm">Glenmore Park, NSW</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Who This Is For */}
      <section className="bg-white border-b border-slate-200">
        <div className="max-w-5xl mx-auto px-6 py-16">
          <div className="text-center mb-12">
            <h2 
              className="text-3xl md:text-4xl font-bold text-slate-900 tracking-tight mb-4"
              style={{ fontFamily: 'Crimson Pro, serif' }}
            >
              Who This Tool May Assist
            </h2>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            <div className="text-center p-6">
              <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Users className="w-8 h-8 text-slate-700" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                Families & Support Networks
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                Organise case materials and identify potential issues to discuss with legal representatives.
              </p>
            </div>

            <div className="text-center p-6">
              <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Scale className="w-8 h-8 text-slate-700" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                Legal Professionals
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                A supplementary research tool to help organise and review case documentation efficiently.
              </p>
            </div>

            <div className="text-center p-6">
              <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <FileText className="w-8 h-8 text-slate-700" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                Researchers & Advocates
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                Analyse case patterns and document potential issues in criminal justice matters.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Secondary Disclaimer */}
      <section className="bg-amber-50 border-y border-amber-200">
        <div className="max-w-4xl mx-auto px-6 py-10">
          <div className="flex items-start gap-4">
            <AlertTriangle className="w-6 h-6 text-amber-700 shrink-0 mt-1" />
            <div>
              <h3 className="text-lg font-semibold text-amber-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
                Important Reminder
              </h3>
              <p className="text-amber-800 leading-relaxed">
                This tool is designed to assist with organisation and research only. It uses AI technology which can make mistakes 
                and may produce inaccurate results. <strong>All outputs must be independently verified by a qualified legal professional.</strong> 
                Users are solely responsible for ensuring they have permission to upload any documents and for complying with all applicable laws.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-slate-900">
        <div className="max-w-4xl mx-auto px-6 py-16 text-center">
          <h2 
            className="text-3xl md:text-4xl font-bold text-white tracking-tight mb-4"
            style={{ fontFamily: 'Crimson Pro, serif' }}
          >
            Ready to Get Started?
          </h2>
          <p className="text-slate-300 text-lg mb-8 max-w-2xl mx-auto">
            Sign in to begin organising your case documents and identifying potential issues for legal review.
          </p>
          <Button
            onClick={handleLogin}
            data-testid="cta-login-btn"
            className="bg-amber-600 text-white hover:bg-amber-700 rounded-md px-8 py-3 text-lg font-medium"
          >
            Sign In with Google
          </Button>
          <p className="text-slate-400 text-sm mt-4">
            By signing in, you agree to our <Link to="/terms" className="underline hover:text-slate-300">Terms of Service</Link>
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-950 border-t border-slate-800">
        <div className="max-w-6xl mx-auto px-6 py-10">
          <div className="grid md:grid-cols-3 gap-8">
            {/* Brand */}
            <div>
              <div className="flex items-center gap-2 mb-4">
                <Scale className="w-6 h-6 text-amber-500" />
                <span className="text-lg text-white font-semibold" style={{ fontFamily: 'Crimson Pro, serif' }}>
                  Appeal Case Manager
                </span>
              </div>
              <p className="text-slate-400 text-sm leading-relaxed">
                A document analysis and case organisation tool for criminal appeal research under NSW and Australian Federal law.
              </p>
            </div>

            {/* Links */}
            <div>
              <h4 className="text-white font-semibold mb-4">Legal</h4>
              <ul className="space-y-2">
                <li>
                  <Link to="/terms" className="text-slate-400 hover:text-white text-sm transition-colors">
                    Terms of Service
                  </Link>
                </li>
                <li>
                  <Link to="/terms" className="text-slate-400 hover:text-white text-sm transition-colors">
                    Privacy Policy
                  </Link>
                </li>
                <li>
                  <Link to="/professional-summary" className="text-slate-400 hover:text-white text-sm transition-colors">
                    For Legal Professionals
                  </Link>
                </li>
              </ul>
            </div>

            {/* Creator */}
            <div>
              <h4 className="text-white font-semibold mb-4">Creator</h4>
              <p className="text-slate-400 text-sm">Debra King</p>
              <p className="text-slate-500 text-sm">Glenmore Park, NSW, Australia</p>
              <p className="text-red-400 text-xs mt-2 font-medium">Not a qualified lawyer</p>
            </div>
          </div>

          <div className="border-t border-slate-800 mt-8 pt-8 text-center">
            <p className="text-slate-500 text-sm">
              © 2025 Appeal Case Manager. This tool does not provide legal advice.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
