import { Scale, ArrowLeft } from "lucide-react";
import { Button } from "../components/ui/button";
import { Link } from "react-router-dom";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-slate-900 px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Scale className="w-8 h-8 text-amber-400" />
            <span className="text-xl font-bold text-white" style={{ fontFamily: 'Crimson Pro, serif' }}>
              Appeal Case Manager
            </span>
          </div>
          <Link to="/">
            <Button variant="outline" className="border-slate-600 text-slate-300 hover:bg-slate-800">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-10">
        <h1 className="text-3xl font-bold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
          Terms of Service & Privacy Policy
        </h1>
        <p className="text-slate-600 mb-8">Last updated: March 2025</p>

        <div className="space-y-8 text-slate-700">
          {/* Introduction */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              1. Introduction
            </h2>
            <p className="mb-3">
              Welcome to Appeal Case Manager ("the Application", "we", "us", "our"). By accessing or using this Application, 
              you ("User", "you", "your") agree to be bound by these Terms of Service and Privacy Policy. If you do not agree 
              to these terms, you must not use this Application.
            </p>
            <p>
              This Application is owned and operated by Debra King, located in Glenmore Park, NSW, Australia.
            </p>
          </section>

          {/* About the Creator */}
          <section className="bg-slate-100 border border-slate-300 rounded-lg p-5">
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              2. About the Creator
            </h2>
            <p className="mb-3 text-slate-700">
              <strong>Debra King is not a qualified lawyer.</strong> She has spent years studying and learning applicable 
              criminal laws herself, becoming so well-educated in NSW and Australian Federal law that she can recite most 
              sections of the relevant Acts without reference.
            </p>
            <p className="mb-3 text-slate-700">
              This Application was created after years of manually searching through case files, comparing and assessing 
              appeals to understand what made them successful or unsuccessful. Debra has put blood, sweat, and tears into 
              this project out of a deep love and commitment to helping her mates.
            </p>
            <p className="text-slate-700 italic">
              "I just wanted to create something that could possibly assist others without them having to spend years 
              working this out themselves. I'm sure this will help lawyers at all levels too."
            </p>
          </section>

          {/* Service Description */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              3. Service Description
            </h2>
            <p>
              The Application provides AI-assisted document analysis and research support tools designed to help users 
              organise case materials and identify potential issues in criminal appeal matters. The Application uses 
              artificial intelligence technology to analyse uploaded documents and generate reports.
            </p>
          </section>

          {/* Not Legal Advice */}
          <section className="bg-amber-50 border border-amber-200 rounded-lg p-5">
            <h2 className="text-xl font-semibold text-amber-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              4. Important: Not Legal Advice
            </h2>
            <p className="mb-3 text-amber-800">
              <strong>The information, analysis, and reports generated by this Application do NOT constitute legal advice</strong> and 
              should not be relied upon as a substitute for advice from a qualified Australian legal practitioner.
            </p>
            <p className="text-amber-800">
              All information generated through this Application is for <strong>informational and research purposes only</strong>. 
              Users must obtain independent legal advice from a qualified legal professional before making any decision or 
              taking any action in relation to an appeal or criminal proceeding.
            </p>
          </section>

          {/* AI Disclaimer */}
          <section className="bg-blue-50 border border-blue-200 rounded-lg p-5">
            <h2 className="text-xl font-semibold text-blue-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              5. AI Technology Disclaimer
            </h2>
            <p className="mb-3 text-blue-800">
              This Application uses artificial intelligence (AI) technology to analyse documents and generate reports. 
              You acknowledge and agree that:
            </p>
            <ul className="list-disc list-inside space-y-2 text-blue-800">
              <li>AI technology can make mistakes and may produce inaccurate, incomplete, or misleading results</li>
              <li>The AI may misinterpret documents, miss relevant information, or draw incorrect conclusions</li>
              <li>No guarantee is made regarding the accuracy, reliability, or completeness of any AI-generated content</li>
              <li>All AI-generated analysis must be independently verified by qualified professionals</li>
              <li>The Application owner accepts no responsibility for errors or omissions in AI-generated content</li>
            </ul>
          </section>

          {/* User Responsibilities */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              6. User Responsibilities
            </h2>
            <p className="mb-3">By using this Application, you agree that:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>You use this Application entirely at your own discretion and risk</li>
              <li>You are solely responsible for ensuring you have the necessary permissions, authority, and legal right to upload any documents or content</li>
              <li>You will not upload any documents without proper authorisation from all relevant parties</li>
              <li>You are responsible for maintaining the confidentiality of any sensitive, privileged, or legally protected documents</li>
              <li>You understand that uploading certain documents may waive legal privilege or confidentiality protections</li>
              <li>You will comply with all applicable laws, including privacy laws and legal professional privilege requirements</li>
            </ul>
          </section>

          {/* Confidentiality Warning */}
          <section className="bg-red-50 border border-red-200 rounded-lg p-5">
            <h2 className="text-xl font-semibold text-red-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              7. Confidentiality & Legal Privilege Warning
            </h2>
            <p className="mb-3 text-red-800">
              <strong>WARNING:</strong> Uploading legal documents to this Application may affect legal professional privilege 
              or confidentiality protections. You should seek legal advice before uploading any privileged or confidential documents.
            </p>
            <p className="text-red-800">
              The Application owner does not guarantee the security or confidentiality of uploaded documents and accepts 
              no responsibility for any loss of privilege or breach of confidentiality arising from your use of this Application.
            </p>
          </section>

          {/* Limitation of Liability */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              8. Limitation of Liability
            </h2>
            <p className="mb-3">
              To the maximum extent permitted by law:
            </p>
            <ul className="list-disc list-inside space-y-2 mb-3">
              <li>The Application is provided "as is" and "as available" without any warranties of any kind, express or implied</li>
              <li>We disclaim all warranties, including but not limited to merchantability, fitness for a particular purpose, and non-infringement</li>
              <li>We shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of the Application</li>
              <li>We shall not be liable for any loss of data, loss of profits, or any damages resulting from reliance on AI-generated content</li>
              <li>Our total liability to you for any claims arising from your use of the Application shall not exceed the amount you paid to us (if any) in the 12 months preceding the claim</li>
            </ul>
            <p>
              Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability, so some of the above 
              limitations may not apply to you. In such cases, our liability will be limited to the maximum extent permitted by law.
            </p>
          </section>

          {/* Indemnification */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              9. Indemnification
            </h2>
            <p>
              You agree to indemnify, defend, and hold harmless the Application owner, Debra King, and any associated parties 
              from and against any and all claims, damages, losses, costs, and expenses (including reasonable legal fees) 
              arising from or related to:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-3">
              <li>Your use of the Application</li>
              <li>Your violation of these Terms of Service</li>
              <li>Your violation of any rights of another party, including intellectual property or privacy rights</li>
              <li>Any content you upload to the Application</li>
              <li>Any claim that your uploaded content caused damage to a third party</li>
            </ul>
          </section>

          {/* Privacy Policy */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              10. Privacy Policy
            </h2>
            
            <h3 className="font-semibold text-slate-800 mt-4 mb-2">9.1 Information We Collect</h3>
            <ul className="list-disc list-inside space-y-1">
              <li>Account information (name, email address) provided through Google authentication</li>
              <li>Documents and content you upload to the Application</li>
              <li>Case information and notes you create within the Application</li>
              <li>Usage data and analytics to improve the service</li>
            </ul>

            <h3 className="font-semibold text-slate-800 mt-4 mb-2">9.2 How We Use Your Information</h3>
            <ul className="list-disc list-inside space-y-1">
              <li>To provide and maintain the Application services</li>
              <li>To process your documents through AI analysis</li>
              <li>To generate reports and analysis as requested</li>
              <li>To improve and develop the Application</li>
            </ul>

            <h3 className="font-semibold text-slate-800 mt-4 mb-2">9.3 Third-Party Services</h3>
            <p>
              This Application uses third-party AI services (including OpenAI) to process and analyse your documents. 
              By using this Application, you consent to your uploaded content being processed by these third-party services 
              in accordance with their respective terms and privacy policies.
            </p>

            <h3 className="font-semibold text-slate-800 mt-4 mb-2">9.4 Data Security</h3>
            <p>
              While we implement reasonable security measures, no method of electronic storage or transmission is 100% secure. 
              We cannot guarantee the absolute security of your data. You upload documents at your own risk.
            </p>
          </section>

          {/* Data Retention */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              11. Data Retention & Deletion
            </h2>
            <p className="mb-3">
              Your data, including uploaded documents, cases, and reports, will be retained for as long as your account is active 
              or as needed to provide services. You may request deletion of your account and associated data by contacting us.
            </p>
            <p>
              Upon account deletion, we will make reasonable efforts to delete your data, though some information may be retained 
              as required by law or for legitimate business purposes (such as resolving disputes or enforcing our agreements).
            </p>
          </section>

          {/* Governing Law */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              12. Governing Law & Jurisdiction
            </h2>
            <p className="mb-3">
              These Terms of Service shall be governed by and construed in accordance with the laws of New South Wales, Australia, 
              without regard to conflict of law principles.
            </p>
            <p>
              Any disputes arising from or relating to these Terms or your use of the Application shall be subject to the 
              exclusive jurisdiction of the courts of New South Wales, Australia.
            </p>
          </section>

          {/* Changes to Terms */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              13. Changes to Terms
            </h2>
            <p>
              We reserve the right to modify these Terms of Service at any time. We will notify users of any material changes 
              by updating the "Last updated" date at the top of this page. Your continued use of the Application after any 
              changes constitutes acceptance of the new terms.
            </p>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              14. Contact Information
            </h2>
            <p>
              If you have any questions about these Terms of Service or Privacy Policy, please contact Debra King at Glenmore Park, NSW, Australia.
            </p>
          </section>

          {/* Acknowledgment */}
          <section className="bg-slate-100 border border-slate-300 rounded-lg p-5">
            <h2 className="text-xl font-semibold text-slate-900 mb-3" style={{ fontFamily: 'Crimson Pro, serif' }}>
              15. Acknowledgment
            </h2>
            <p>
              By using this Application, you acknowledge that you have read, understood, and agree to be bound by these 
              Terms of Service and Privacy Policy. If you do not agree to these terms, you must immediately cease using the Application.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-slate-900 px-6 py-6 mt-10">
        <div className="max-w-4xl mx-auto text-center text-slate-400 text-sm">
          <p>© 2025 Appeal Case Manager. All rights reserved.</p>
          <p className="mt-2">Created by Debra King — Glenmore Park, NSW</p>
        </div>
      </footer>
    </div>
  );
};

export default TermsOfService;
